### ISSUE TITLE
how to fetchaddr from outgoing mails?

### ISSUE THREAD

**Issue by stef** [RolandRosenfeld/lbdb#7]
hey, long-time super happy user of lbdb. i recently had to setup a new system, and my outgoing mails get truncated on them. i traced it to my sendmail wrapper which calls lbdb-fetchaddr, for years i used this:

```
#!/bin/bash
tee >(lbdb-fetchaddr -a)|/usr/sbin/sendmail -oem -oi $@
```

i minimized the testcase to this (/tmp/x is a random mail i sent):

```
%  wc -l </tmp/x; tee >(lbdb-fetchaddr -a) </tmp/x | wc -l
1546
957
```

it seems the pipe is closed early and the wc at the end of the pipe gets only truncated output. if i replace the lbdb-fetchaddr with `cat >/dev/null` the final wc at the end of the pipe gets the correct number of lines.

now i understand that you recommend using lbdb-fetchaddr in procmail (which is btw considered harmful[1]) for incoming mails, but i would like to avoid that since that also has unsolicited mails coming in with addresses i don't want added to my lbdb, i prefer only mails in lbdb that i sent mail to. i think i found this sendmail wrapper somewhere decades ago online[2].

i fixed/workarounded this issue by appending an extra 
```
cat >/dev/null
```

at the end of `lbdb-fetchaddr`. maybe this is something for you to consider as a permanent solution to this issue (which others also might encounter).

kudos for your work on lbdb!

[1] https://anarc.at/blog/2022-03-02-procmail-considered-harmful/
[2] https://www.mail-archive.com/mutt-users@mutt.org/msg27678.html

**Comment by RolandRosenfeld** [comment]
Hi stef,
thank you for your report.

To say the truth, I never used process substitution before and first head to learn how it works.
The problem here seem to be that lbdb-fetchaddr pipes the file to fetchaddr, which only parses the header and stops processing after reading the empty line between header and body of the mail.

The same happens with true as command:
```
wc -l < /tmp/y; tee >(true) < /tmp/y | wc -l
2613
245
```
So you're right, doing a 
`cat > /dev/null 
`
seems to be a good solution/workaround in this setup.

I just committed this in https://github.com/RolandRosenfeld/lbdb/commit/ecc7d74edf1caa2bcff2441cfbbe16f4472b05e6.

**Comment by stef** [comment]
super-duper! btw sorry for not saying explicitly that processing stops after headers, that was kinda obvious to me.

thanks a lot for all your efforts! kudos again,s
